// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC78E6oX_aitbEAHsz8JZWgMkCwpNxvbGI',
    appId: '1:193087041235:web:3d6321d2a488cdbc24ae26',
    messagingSenderId: '193087041235',
    projectId: 'vibetesting-1cr',
    authDomain: 'vibetesting-1cr.firebaseapp.com',
    storageBucket: 'vibetesting-1cr.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC78E6oX_aitbEAHsz8JZWgMkCwpNxvbGI',
    appId: '1:193087041235:web:3d6321d2a488cdbc24ae26',
    messagingSenderId: '193087041235',
    projectId: 'vibetesting-1cr',
    authDomain: 'vibetesting-1cr.firebaseapp.com',
    storageBucket: 'vibetesting-1cr.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7gtF0hm6v9r7CT-aC1-XjmZtpMQKu5Co',
    appId: '1:193087041235:ios:7ebef7acb6fc0c4124ae26',
    messagingSenderId: '193087041235',
    projectId: 'vibetesting-1cr',
    storageBucket: 'vibetesting-1cr.firebasestorage.app',
    iosClientId: '193087041235-mfa86rs0uol6rin70c4q0u78th1gtidc.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibematictester',
  );

}